*** Starting uWSGI 2.0.18 (64bit) on [Mon Jul  1 14:31:15 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 30 June 2019 12:33:41
os: Linux-3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019
nodename: VM_0_17_centos
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/django/mywebsite
writing pidfile to /root/django/mywebsite/script/uwsgi.pid
detected binary path: /root/.pyenv/versions/3.7.3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/django/mywebsite/
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 3881
your memory page size is 4096 bytes
detected max file descriptor number: 100001
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /root/django/mywebsite/script/uwsgi.sock fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.3 (default, Jun 30 2019, 12:36:01)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xaa5c00
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72920 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xaa5c00 pid: 14917 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 14917, cores: 1)
*** Starting uWSGI 2.0.18 (64bit) on [Mon Jul  1 14:33:34 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 30 June 2019 12:33:41
os: Linux-3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019
nodename: VM_0_17_centos
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/django/mywebsite
writing pidfile to /root/django/mywebsite/script/uwsgi.pid
detected binary path: /root/.pyenv/versions/3.7.3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/django/mywebsite/
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 3881
your memory page size is 4096 bytes
detected max file descriptor number: 100001
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:9090 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.3 (default, Jun 30 2019, 12:36:01)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x280b0f0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72920 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x280b0f0 pid: 15175 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 15175, cores: 1)
[pid: 15175|app: 0|req: 1/1] 59.108.165.58 () {42 vars in 739 bytes} [Mon Jul  1 06:34:00 2019] GET / => generated 14 bytes in 5 msecs (HTTP/1.1 200) 3 headers in 108 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.18 (64bit) on [Mon Jul  1 15:19:36 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 30 June 2019 12:33:41
os: Linux-3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019
nodename: VM_0_17_centos
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/django/mywebsite
writing pidfile to /root/django/mywebsite/script/uwsgi.pid
detected binary path: /root/.pyenv/versions/3.7.3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/django/mywebsite/
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 3881
your memory page size is 4096 bytes
detected max file descriptor number: 100001
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:9090 fd 4
spawned uWSGI http 1 (pid: 18969)
uwsgi socket 0 bound to TCP address 127.0.0.1:46011 (port auto-assigned) fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.3 (default, Jun 30 2019, 12:36:01)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xe0d270
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72920 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0xe0d270 pid: 18968 (default app)
mountpoint  already configured. skip.
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 18968, cores: 1)
[pid: 18968|app: 0|req: 1/1] 59.108.165.58 () {38 vars in 692 bytes} [Mon Jul  1 07:19:41 2019] GET / => generated 14 bytes in 7 msecs (HTTP/1.1 200) 3 headers in 108 bytes (1 switches on core 0)
[pid: 18968|app: 0|req: 2/2] 59.108.165.58 () {38 vars in 692 bytes} [Mon Jul  1 07:19:43 2019] GET / => generated 14 bytes in 0 msecs (HTTP/1.1 200) 3 headers in 108 bytes (1 switches on core 0)
[pid: 18968|app: 0|req: 3/3] 59.108.165.58 () {38 vars in 686 bytes} [Mon Jul  1 07:20:06 2019] GET / => generated 14 bytes in 0 msecs (HTTP/1.1 200) 3 headers in 108 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 18968|app: 0|req: 4/4] 59.108.165.58 () {36 vars in 646 bytes} [Mon Jul  1 07:20:06 2019] GET /favicon.ico => generated 2082 bytes in 6 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.18 (64bit) on [Mon Jul  1 15:21:00 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 30 June 2019 12:33:41
os: Linux-3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019
nodename: VM_0_17_centos
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/django/mywebsite
writing pidfile to /root/django/mywebsite/script/uwsgi.pid
detected binary path: /root/.pyenv/versions/3.7.3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/django/mywebsite/
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 3881
your memory page size is 4096 bytes
detected max file descriptor number: 100001
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
The -s/--socket option is missing and stdin is not a socket.
*** Starting uWSGI 2.0.18 (64bit) on [Mon Jul  1 15:21:53 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 30 June 2019 12:33:41
os: Linux-3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019
nodename: VM_0_17_centos
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/django/mywebsite
writing pidfile to /root/django/mywebsite/script/uwsgi.pid
detected binary path: /root/.pyenv/versions/3.7.3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/django/mywebsite/
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 3881
your memory page size is 4096 bytes
detected max file descriptor number: 100001
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:9090 fd 4
spawned uWSGI http 1 (pid: 19281)
uwsgi socket 0 bound to TCP address 127.0.0.1:34980 (port auto-assigned) fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.3 (default, Jun 30 2019, 12:36:01)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x122f250
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72920 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x122f250 pid: 19280 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 19280, cores: 1)
[pid: 19280|app: 0|req: 1/1] 59.108.165.58 () {38 vars in 693 bytes} [Mon Jul  1 07:21:57 2019] GET / => generated 14 bytes in 5 msecs (HTTP/1.1 200) 3 headers in 108 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.18 (64bit) on [Mon Jul  1 15:27:48 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 30 June 2019 12:33:41
os: Linux-3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019
nodename: VM_0_17_centos
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/django/mywebsite
writing pidfile to /root/django/mywebsite/script/uwsgi.pid
detected binary path: /root/.pyenv/versions/3.7.3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/django/mywebsite/
your processes number limit is 3881
limiting address space of processes...
your process address space limit is 134217728 bytes (128 MB)
your memory page size is 4096 bytes
detected max file descriptor number: 100001
VirtualHosting mode enabled.
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:9090 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.3 (default, Jun 30 2019, 12:36:01)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x2980290
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 177648 bytes (173 KB) for 1 cores
*** Operational MODE: single process ***
Traceback (most recent call last):
  File "./mywebsite/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 19825)
spawned uWSGI worker 1 (pid: 19826, cores: 1)
--- no python application found, check your startup logs for errors ---
129.28.167.123 [pid: 19826|app: -1|req: -1/1] 59.108.165.58 () {42 vars in 739 bytes} [Mon Jul  1 15:27:57 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
129.28.167.123 [pid: 19826|app: -1|req: -1/2] 59.108.165.58 () {44 vars in 770 bytes} [Mon Jul  1 15:28:00 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
*** Starting uWSGI 2.0.18 (64bit) on [Mon Jul  1 15:28:34 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 30 June 2019 12:33:41
os: Linux-3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019
nodename: VM_0_17_centos
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/django/mywebsite
writing pidfile to /root/django/mywebsite/script/uwsgi.pid
detected binary path: /root/.pyenv/versions/3.7.3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/django/mywebsite/
your processes number limit is 3881
limiting address space of processes...
your process address space limit is 134217728 bytes (128 MB)
your memory page size is 4096 bytes
detected max file descriptor number: 100001
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:9090 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.3 (default, Jun 30 2019, 12:36:01)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x12c6230
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 177648 bytes (173 KB) for 1 cores
*** Operational MODE: single process ***
Traceback (most recent call last):
  File "./mywebsite/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/core/wsgi.py", line 2, in <module>
    from django.core.handlers.wsgi import WSGIHandler
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/core/handlers/wsgi.py", line 8, in <module>
    from django.core.handlers import base
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/core/handlers/base.py", line 8, in <module>
    from django.urls import get_resolver, set_urlconf
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/urls/__init__.py", line 1, in <module>
    from .base import (
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/urls/base.py", line 8, in <module>
    from .exceptions import NoReverseMatch, Resolver404
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/urls/exceptions.py", line 1, in <module>
    from django.http import Http404
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/http/__init__.py", line 5, in <module>
    from django.http.response import (
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/http/response.py", line 15, in <module>
    from django.core.serializers.json import DjangoJSONEncoder
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/core/serializers/__init__.py", line 23, in <module>
    from django.core.serializers.base import SerializerDoesNotExist
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/core/serializers/base.py", line 7, in <module>
    from django.db import models
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/db/models/__init__.py", line 28, in <module>
    from django.db.models.base import DEFERRED, Model  # isort:skip
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
MemoryError
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 19965)
spawned uWSGI worker 1 (pid: 19966, cores: 1)
--- no python application found, check your startup logs for errors ---
[pid: 19966|app: -1|req: -1/1] 59.108.165.58 () {42 vars in 740 bytes} [Mon Jul  1 15:28:36 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 19966|app: -1|req: -1/2] 59.108.165.58 () {42 vars in 740 bytes} [Mon Jul  1 15:28:37 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 19966|app: -1|req: -1/3] 59.108.165.58 () {40 vars in 708 bytes} [Mon Jul  1 15:28:41 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
*** Starting uWSGI 2.0.18 (64bit) on [Mon Jul  1 15:29:13 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 30 June 2019 12:33:41
os: Linux-3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019
nodename: VM_0_17_centos
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/django/mywebsite
writing pidfile to /root/django/mywebsite/script/uwsgi.pid
detected binary path: /root/.pyenv/versions/3.7.3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/django/mywebsite/
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 3881
limiting address space of processes...
your process address space limit is 134217728 bytes (128 MB)
your memory page size is 4096 bytes
detected max file descriptor number: 100001
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:9090 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.3 (default, Jun 30 2019, 12:36:01)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x24981b0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 88824 bytes (86 KB) for 1 cores
*** Operational MODE: single process ***
Traceback (most recent call last):
  File "./mywebsite/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/core/wsgi.py", line 2, in <module>
    from django.core.handlers.wsgi import WSGIHandler
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/core/handlers/wsgi.py", line 8, in <module>
    from django.core.handlers import base
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/core/handlers/base.py", line 8, in <module>
    from django.urls import get_resolver, set_urlconf
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/urls/__init__.py", line 1, in <module>
    from .base import (
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/urls/base.py", line 8, in <module>
    from .exceptions import NoReverseMatch, Resolver404
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/urls/exceptions.py", line 1, in <module>
    from django.http import Http404
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/http/__init__.py", line 5, in <module>
    from django.http.response import (
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/http/response.py", line 15, in <module>
    from django.core.serializers.json import DjangoJSONEncoder
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/core/serializers/__init__.py", line 23, in <module>
    from django.core.serializers.base import SerializerDoesNotExist
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/core/serializers/base.py", line 7, in <module>
    from django.db import models
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/db/models/__init__.py", line 28, in <module>
    from django.db.models.base import DEFERRED, Model  # isort:skip
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 818, in get_code
  File "<frozen importlib._bootstrap_external>", line 917, in get_data
MemoryError
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 20103, cores: 1)
--- no python application found, check your startup logs for errors ---
[pid: 20103|app: -1|req: -1/1] 59.108.165.58 () {42 vars in 739 bytes} [Mon Jul  1 15:29:16 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
VACUUM: pidfile removed.
*** Starting uWSGI 2.0.18 (64bit) on [Mon Jul  1 15:29:38 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 30 June 2019 12:33:41
os: Linux-3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019
nodename: VM_0_17_centos
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/django/mywebsite
writing pidfile to /root/django/mywebsite/script/uwsgi.pid
detected binary path: /root/.pyenv/versions/3.7.3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/django/mywebsite/
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 3881
limiting address space of processes...
your process address space limit is 134217728 bytes (128 MB)
your memory page size is 4096 bytes
detected max file descriptor number: 100001
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:9090 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.3 (default, Jun 30 2019, 12:36:01)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1991130
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 88824 bytes (86 KB) for 1 cores
*** Operational MODE: single process ***
Traceback (most recent call last):
  File "./mywebsite/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/core/wsgi.py", line 2, in <module>
    from django.core.handlers.wsgi import WSGIHandler
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/core/handlers/wsgi.py", line 8, in <module>
    from django.core.handlers import base
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/core/handlers/base.py", line 8, in <module>
    from django.urls import get_resolver, set_urlconf
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/urls/__init__.py", line 1, in <module>
    from .base import (
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/urls/base.py", line 8, in <module>
    from .exceptions import NoReverseMatch, Resolver404
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/urls/exceptions.py", line 1, in <module>
    from django.http import Http404
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/http/__init__.py", line 5, in <module>
    from django.http.response import (
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/http/response.py", line 15, in <module>
    from django.core.serializers.json import DjangoJSONEncoder
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/core/serializers/__init__.py", line 23, in <module>
    from django.core.serializers.base import SerializerDoesNotExist
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/core/serializers/base.py", line 7, in <module>
    from django.db import models
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/db/models/__init__.py", line 28, in <module>
    from django.db.models.base import DEFERRED, Model  # isort:skip
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 818, in get_code
  File "<frozen importlib._bootstrap_external>", line 917, in get_data
MemoryError
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 20194, cores: 1)
--- no python application found, check your startup logs for errors ---
[pid: 20194|app: -1|req: -1/1] 59.108.165.58 () {42 vars in 739 bytes} [Mon Jul  1 15:29:41 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 20194|app: -1|req: -1/2] 59.108.165.58 () {42 vars in 739 bytes} [Mon Jul  1 15:29:42 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 20194|app: -1|req: -1/3] 59.108.165.58 () {42 vars in 739 bytes} [Mon Jul  1 15:29:42 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 20194|app: -1|req: -1/4] 59.108.165.58 () {42 vars in 739 bytes} [Mon Jul  1 15:29:46 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
*** Starting uWSGI 2.0.18 (64bit) on [Mon Jul  1 15:32:17 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 30 June 2019 12:33:41
os: Linux-3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019
nodename: VM_0_17_centos
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/django/mywebsite
writing pidfile to /root/django/mywebsite/script/uwsgi.pid
detected binary path: /root/.pyenv/versions/3.7.3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/django/mywebsite/
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 3881
your memory page size is 4096 bytes
detected max file descriptor number: 100001
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:9090 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.3 (default, Jun 30 2019, 12:36:01)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x257b150
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72920 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x257b150 pid: 20513 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 20513, cores: 1)
[pid: 20513|app: 0|req: 1/1] 59.108.165.58 () {42 vars in 739 bytes} [Mon Jul  1 07:32:19 2019] GET / => generated 14 bytes in 6 msecs (HTTP/1.1 200) 3 headers in 108 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.18 (64bit) on [Mon Jul  1 15:33:01 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 30 June 2019 12:33:41
os: Linux-3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019
nodename: VM_0_17_centos
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/django/mywebsite
writing pidfile to /root/django/mywebsite/script/uwsgi.pid
detected binary path: /root/.pyenv/versions/3.7.3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/django/mywebsite/
your processes number limit is 3881
your memory page size is 4096 bytes
detected max file descriptor number: 100001
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:9090 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.3 (default, Jun 30 2019, 12:36:01)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x15701c0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x15701c0 pid: 20621 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 20621)
spawned uWSGI worker 1 (pid: 20633, cores: 1)
[pid: 20633|app: 0|req: 1/1] 59.108.165.58 () {42 vars in 739 bytes} [Mon Jul  1 07:33:03 2019] GET / => generated 14 bytes in 8 msecs (HTTP/1.1 200) 3 headers in 108 bytes (1 switches on core 0)
[pid: 20633|app: 0|req: 2/2] 59.108.165.58 () {42 vars in 739 bytes} [Mon Jul  1 07:33:04 2019] GET / => generated 14 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 108 bytes (1 switches on core 0)
[pid: 20633|app: 0|req: 3/3] 59.108.165.58 () {42 vars in 739 bytes} [Mon Jul  1 07:33:04 2019] GET / => generated 14 bytes in 0 msecs (HTTP/1.1 200) 3 headers in 108 bytes (1 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.18 (64bit) on [Mon Jul  1 15:33:32 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 30 June 2019 12:33:41
os: Linux-3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019
nodename: VM_0_17_centos
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/django/mywebsite
writing pidfile to /root/django/mywebsite/script/uwsgi.pid
detected binary path: /root/.pyenv/versions/3.7.3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/django/mywebsite/
your processes number limit is 3881
your memory page size is 4096 bytes
detected max file descriptor number: 100001
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:9090 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.3 (default, Jun 30 2019, 12:36:01)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x29271a0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218760 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x29271a0 pid: 20744 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 20744)
spawned uWSGI worker 1 (pid: 20746, cores: 1)
spawned uWSGI worker 2 (pid: 20747, cores: 1)
[pid: 20746|app: 0|req: 1/1] 59.108.165.58 () {42 vars in 739 bytes} [Mon Jul  1 07:33:35 2019] GET / => generated 14 bytes in 8 msecs (HTTP/1.1 200) 3 headers in 108 bytes (1 switches on core 0)
[pid: 20747|app: 0|req: 1/2] 59.108.165.58 () {42 vars in 739 bytes} [Mon Jul  1 07:33:35 2019] GET / => generated 14 bytes in 8 msecs (HTTP/1.1 200) 3 headers in 108 bytes (1 switches on core 0)
[pid: 20747|app: 0|req: 2/3] 59.108.165.58 () {42 vars in 739 bytes} [Mon Jul  1 07:33:36 2019] GET / => generated 14 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 108 bytes (1 switches on core 0)
[pid: 20746|app: 0|req: 2/4] 59.108.165.58 () {42 vars in 739 bytes} [Mon Jul  1 07:33:36 2019] GET / => generated 14 bytes in 0 msecs (HTTP/1.1 200) 3 headers in 108 bytes (1 switches on core 0)
[pid: 20746|app: 0|req: 3/5] 59.108.165.58 () {42 vars in 739 bytes} [Mon Jul  1 07:33:37 2019] GET / => generated 14 bytes in 0 msecs (HTTP/1.1 200) 3 headers in 108 bytes (1 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.18 (64bit) on [Mon Jul  1 15:34:13 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 30 June 2019 12:33:41
os: Linux-3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019
nodename: VM_0_17_centos
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/django/mywebsite
writing pidfile to /root/django/mywebsite/script/uwsgi.pid
detected binary path: /root/.pyenv/versions/3.7.3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/django/mywebsite/
your processes number limit is 3881
your memory page size is 4096 bytes
detected max file descriptor number: 100001
VirtualHosting mode enabled.
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:9090 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.3 (default, Jun 30 2019, 12:36:01)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xcba200
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218760 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0xcba200 pid: 20891 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 20891)
spawned uWSGI worker 1 (pid: 20892, cores: 1)
spawned uWSGI worker 2 (pid: 20893, cores: 1)
foolpanda.com [pid: 20892|app: 0|req: 1/1] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 07:34:15 2019] GET / => generated 14 bytes in 8 msecs (HTTP/1.1 200) 3 headers in 108 bytes (1 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.18 (64bit) on [Mon Jul  1 15:34:49 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 30 June 2019 12:33:41
os: Linux-3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019
nodename: VM_0_17_centos
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/django/mywebsite
writing pidfile to /root/django/mywebsite/script/uwsgi.pid
detected binary path: /root/.pyenv/versions/3.7.3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/django/mywebsite/
your processes number limit is 3881
your memory page size is 4096 bytes
detected max file descriptor number: 100001
VirtualHosting mode enabled.
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:9090 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.3 (default, Jun 30 2019, 12:36:01)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1124210
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218760 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "./mywebsite/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 20992)
spawned uWSGI worker 1 (pid: 20993, cores: 1)
spawned uWSGI worker 2 (pid: 20994, cores: 1)
--- no python application found, check your startup logs for errors ---
foolpanda.com [pid: 20994|app: -1|req: -1/1] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 15:34:51 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
foolpanda.com [pid: 20994|app: -1|req: -1/2] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 15:34:52 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
foolpanda.com [pid: 20994|app: -1|req: -1/3] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 15:34:52 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
foolpanda.com [pid: 20993|app: -1|req: -1/4] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 15:34:52 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
foolpanda.com [pid: 20994|app: -1|req: -1/5] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 15:34:53 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "./mywebsite/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
unable to load app 0 (mountpoint='foolpanda.com|') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
foolpanda.com [pid: 20994|app: -1|req: -1/6] 59.108.165.58 () {48 vars in 836 bytes} [Mon Jul  1 15:39:45 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.18 (64bit) on [Mon Jul  1 15:40:21 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 30 June 2019 12:33:41
os: Linux-3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019
nodename: VM_0_17_centos
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/django/mywebsite
writing pidfile to /root/django/mywebsite/script/uwsgi.pid
detected binary path: /root/.pyenv/versions/3.7.3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 3881
your memory page size is 4096 bytes
detected max file descriptor number: 100001
VirtualHosting mode enabled.
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:9090 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.3 (default, Jun 30 2019, 12:36:01)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x116c1e0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218760 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 21528)
spawned uWSGI worker 1 (pid: 21529, cores: 1)
spawned uWSGI worker 2 (pid: 21530, cores: 1)
Traceback (most recent call last):
  File "./mywebsite/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
unable to load app 0 (mountpoint='foolpanda.com|') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
foolpanda.com [pid: 21530|app: -1|req: -1/1] 59.108.165.58 () {48 vars in 836 bytes} [Mon Jul  1 15:40:25 2019] GET / => generated 21 bytes in 1 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "./mywebsite/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
unable to load app 0 (mountpoint='foolpanda.com|') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
foolpanda.com [pid: 21530|app: -1|req: -1/2] 59.108.165.58 () {48 vars in 836 bytes} [Mon Jul  1 15:40:27 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "./mywebsite/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
unable to load app 0 (mountpoint='foolpanda.com|') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
foolpanda.com [pid: 21529|app: -1|req: -1/3] 59.108.165.58 () {48 vars in 836 bytes} [Mon Jul  1 15:40:27 2019] GET / => generated 21 bytes in 1 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "./mywebsite/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
unable to load app 0 (mountpoint='foolpanda.com|') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
foolpanda.com [pid: 21530|app: -1|req: -1/4] 59.108.165.58 () {48 vars in 836 bytes} [Mon Jul  1 15:40:28 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "./mywebsite/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
unable to load app 0 (mountpoint='foolpanda.com|') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
foolpanda.com [pid: 21530|app: -1|req: -1/5] 59.108.165.58 () {48 vars in 836 bytes} [Mon Jul  1 15:40:28 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
ModuleNotFoundError: No module named '.'
unable to load app 0 (mountpoint='foolpanda.com|') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
foolpanda.com [pid: 21530|app: -1|req: -1/6] 59.108.165.58 () {48 vars in 839 bytes} [Mon Jul  1 15:41:47 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
ModuleNotFoundError: No module named '.'
unable to load app 0 (mountpoint='foolpanda.com|') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
foolpanda.com [pid: 21530|app: -1|req: -1/7] 59.108.165.58 () {48 vars in 839 bytes} [Mon Jul  1 15:41:48 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
ModuleNotFoundError: No module named '.'
unable to load app 0 (mountpoint='129.28.167.123:80|') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
129.28.167.123:80 [pid: 21530|app: -1|req: -1/8] 84.42.174.13 () {38 vars in 564 bytes} [Mon Jul  1 15:42:12 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "./mywebsite/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
unable to load app 0 (mountpoint='foolpanda.com|') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
foolpanda.com [pid: 21530|app: -1|req: -1/9] 59.108.165.58 () {48 vars in 848 bytes} [Mon Jul  1 15:49:40 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "./mywebsite/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
unable to load app 0 (mountpoint='foolpanda.com|') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
foolpanda.com [pid: 21530|app: -1|req: -1/10] 59.108.165.58 () {48 vars in 848 bytes} [Mon Jul  1 15:49:40 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "./mywebsite/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
unable to load app 0 (mountpoint='foolpanda.com|') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
foolpanda.com [pid: 21530|app: -1|req: -1/11] 59.108.165.58 () {48 vars in 848 bytes} [Mon Jul  1 15:49:41 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "./mywebsite/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
ModuleNotFoundError: No module named 'django'
unable to load app 0 (mountpoint='foolpanda.com|') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
foolpanda.com [pid: 21529|app: -1|req: -1/12] 59.108.165.58 () {48 vars in 848 bytes} [Mon Jul  1 15:49:41 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
ModuleNotFoundError: No module named 'mywebsite.mywebsite'
unable to load app 0 (mountpoint='foolpanda.com|') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
foolpanda.com [pid: 21530|app: -1|req: -1/13] 59.108.165.58 () {48 vars in 846 bytes} [Mon Jul  1 15:53:56 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
ModuleNotFoundError: No module named 'mywebsite.mywebsite'
unable to load app 0 (mountpoint='foolpanda.com|') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
foolpanda.com [pid: 21530|app: -1|req: -1/14] 59.108.165.58 () {48 vars in 846 bytes} [Mon Jul  1 15:53:57 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
*** Starting uWSGI 2.0.18 (64bit) on [Mon Jul  1 15:54:06 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 30 June 2019 12:33:41
os: Linux-3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019
nodename: VM_0_17_centos
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/django/mywebsite
writing pidfile to /root/django/mywebsite/script/uwsgi.pid
detected binary path: /root/.pyenv/versions/3.7.3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 3881
your memory page size is 4096 bytes
detected max file descriptor number: 100001
VirtualHosting mode enabled.
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.1:9090).
bind(): Address already in use [core/socket.c line 769]
ModuleNotFoundError: No module named 'mywebsite.mywebsite'
unable to load app 0 (mountpoint='foolpanda.com|') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
foolpanda.com [pid: 21530|app: -1|req: -1/15] 18.236.182.50 () {38 vars in 475 bytes} [Mon Jul  1 15:54:26 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
*** Starting uWSGI 2.0.18 (64bit) on [Mon Jul  1 15:55:58 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 30 June 2019 12:33:41
os: Linux-3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019
nodename: VM_0_17_centos
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/django/mywebsite
writing pidfile to /root/django/mywebsite/script/uwsgi.pid
detected binary path: /root/.pyenv/versions/3.7.3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/django/mywebsite/
your processes number limit is 3881
your memory page size is 4096 bytes
detected max file descriptor number: 100001
VirtualHosting mode enabled.
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:9090 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.3 (default, Jun 30 2019, 12:36:01)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x270e200
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218760 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x270e200 pid: 22910 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 22910)
spawned uWSGI worker 1 (pid: 22916, cores: 1)
spawned uWSGI worker 2 (pid: 22917, cores: 1)
ModuleNotFoundError: No module named 'mywebsite.mywebsite'
unable to load app 1 (mountpoint='foolpanda.com|') (callable not found or import error)
foolpanda.com [pid: 22917|app: 0|req: 1/1] 59.108.165.58 () {48 vars in 846 bytes} [Mon Jul  1 07:56:01 2019] GET / => generated 14 bytes in 56 msecs (HTTP/1.1 200) 3 headers in 108 bytes (1 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.18 (64bit) on [Mon Jul  1 15:57:01 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 30 June 2019 12:33:41
os: Linux-3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019
nodename: VM_0_17_centos
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/django/mywebsite
writing pidfile to /root/django/mywebsite/script/uwsgi.pid
detected binary path: /root/.pyenv/versions/3.7.3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/django/mywebsite/
your processes number limit is 3881
your memory page size is 4096 bytes
detected max file descriptor number: 100001
VirtualHosting mode enabled.
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /root/django/mywebsite/script/uwsgi.sock fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.3 (default, Jun 30 2019, 12:36:01)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1328ce0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218760 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1328ce0 pid: 23067 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 23067)
spawned uWSGI worker 1 (pid: 23068, cores: 1)
spawned uWSGI worker 2 (pid: 23069, cores: 1)
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.18 (64bit) on [Mon Jul  1 16:01:50 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 30 June 2019 12:33:41
os: Linux-3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019
nodename: VM_0_17_centos
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/django/mywebsite
writing pidfile to /root/django/mywebsite/script/uwsgi.pid
detected binary path: /root/.pyenv/versions/3.7.3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/django/mywebsite/
your processes number limit is 3881
your memory page size is 4096 bytes
detected max file descriptor number: 100001
VirtualHosting mode enabled.
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /root/django/mywebsite/script/uwsgi.sock fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.3 (default, Jun 30 2019, 12:36:01)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1ee0ce0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218760 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x1ee0ce0 pid: 23553 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 23553)
spawned uWSGI worker 1 (pid: 23554, cores: 1)
spawned uWSGI worker 2 (pid: 23555, cores: 1)
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.18 (64bit) on [Mon Jul  1 16:11:19 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 30 June 2019 12:33:41
os: Linux-3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019
nodename: VM_0_17_centos
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/django/mywebsite
writing pidfile to /root/django/mywebsite/script/uwsgi.pid
detected binary path: /root/.pyenv/versions/3.7.3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/django/mywebsite/
your processes number limit is 3881
limiting address space of processes...
your process address space limit is 134217728 bytes (128 MB)
your memory page size is 4096 bytes
detected max file descriptor number: 100001
VirtualHosting mode enabled.
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:9090 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.3 (default, Jun 30 2019, 12:36:01)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1632230
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 177648 bytes (173 KB) for 1 cores
*** Operational MODE: single process ***
Traceback (most recent call last):
  File "./mywebsite/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/core/wsgi.py", line 2, in <module>
    from django.core.handlers.wsgi import WSGIHandler
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/core/handlers/wsgi.py", line 8, in <module>
    from django.core.handlers import base
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/core/handlers/base.py", line 8, in <module>
    from django.urls import get_resolver, set_urlconf
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/urls/__init__.py", line 1, in <module>
    from .base import (
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/urls/base.py", line 8, in <module>
    from .exceptions import NoReverseMatch, Resolver404
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/urls/exceptions.py", line 1, in <module>
    from django.http import Http404
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/http/__init__.py", line 5, in <module>
    from django.http.response import (
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/http/response.py", line 15, in <module>
    from django.core.serializers.json import DjangoJSONEncoder
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/core/serializers/__init__.py", line 23, in <module>
    from django.core.serializers.base import SerializerDoesNotExist
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/core/serializers/base.py", line 7, in <module>
    from django.db import models
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/db/models/__init__.py", line 28, in <module>
    from django.db.models.base import DEFERRED, Model  # isort:skip
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
MemoryError
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 24702)
spawned uWSGI worker 1 (pid: 24703, cores: 1)
--- no python application found, check your startup logs for errors ---
foolpanda.com [pid: 24703|app: -1|req: -1/1] 59.108.165.58 () {42 vars in 737 bytes} [Mon Jul  1 16:11:28 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
foolpanda.com [pid: 24703|app: -1|req: -1/2] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 16:11:29 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
foolpanda.com [pid: 24703|app: -1|req: -1/3] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 16:11:30 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
foolpanda.com [pid: 24703|app: -1|req: -1/4] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 16:11:31 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
foolpanda.com [pid: 24703|app: -1|req: -1/5] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 16:11:31 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
foolpanda.com [pid: 24703|app: -1|req: -1/6] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 16:11:35 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
foolpanda.com [pid: 24703|app: -1|req: -1/7] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 16:11:35 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
foolpanda.com [pid: 24703|app: -1|req: -1/8] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 16:11:36 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
foolpanda.com [pid: 24703|app: -1|req: -1/9] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 16:11:36 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
*** Starting uWSGI 2.0.18 (64bit) on [Mon Jul  1 16:12:14 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 30 June 2019 12:33:41
os: Linux-3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019
nodename: VM_0_17_centos
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/django/mywebsite
writing pidfile to /root/django/mywebsite/script/uwsgi.pid
detected binary path: /root/.pyenv/versions/3.7.3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/django/mywebsite/
your processes number limit is 3881
your memory page size is 4096 bytes
detected max file descriptor number: 100001
VirtualHosting mode enabled.
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:9090 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.3 (default, Jun 30 2019, 12:36:01)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x139e230
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x139e230 pid: 24896 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 24896)
spawned uWSGI worker 1 (pid: 24897, cores: 1)
foolpanda.com [pid: 24897|app: 0|req: 1/1] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 08:12:16 2019] GET / => generated 14 bytes in 8 msecs (HTTP/1.1 200) 3 headers in 108 bytes (1 switches on core 0)
foolpanda.com [pid: 24897|app: 0|req: 2/2] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 08:12:17 2019] GET / => generated 14 bytes in 0 msecs (HTTP/1.1 200) 3 headers in 108 bytes (1 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.18 (64bit) on [Mon Jul  1 16:12:50 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 30 June 2019 12:33:41
os: Linux-3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019
nodename: VM_0_17_centos
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/django/mywebsite
writing pidfile to /root/django/mywebsite/script/uwsgi.pid
detected binary path: /root/.pyenv/versions/3.7.3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/django/mywebsite/
your processes number limit is 3881
your memory page size is 4096 bytes
detected max file descriptor number: 100001
VirtualHosting mode enabled.
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:9090 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.3 (default, Jun 30 2019, 12:36:01)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x187e270
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 177648 bytes (173 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x187e270 pid: 25026 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 25026)
spawned uWSGI worker 1 (pid: 25027, cores: 1)
foolpanda.com [pid: 25027|app: 0|req: 1/1] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 08:12:52 2019] GET / => generated 14 bytes in 9 msecs (HTTP/1.1 200) 3 headers in 108 bytes (1 switches on core 0)
foolpanda.com [pid: 25027|app: 0|req: 2/2] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 08:12:53 2019] GET / => generated 14 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 108 bytes (1 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.18 (64bit) on [Mon Jul  1 16:13:11 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 30 June 2019 12:33:41
os: Linux-3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019
nodename: VM_0_17_centos
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/django/mywebsite
writing pidfile to /root/django/mywebsite/script/uwsgi.pid
detected binary path: /root/.pyenv/versions/3.7.3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/django/mywebsite/
your processes number limit is 3881
limiting address space of processes...
your process address space limit is 134217728 bytes (128 MB)
your memory page size is 4096 bytes
detected max file descriptor number: 100001
VirtualHosting mode enabled.
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:9090 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.3 (default, Jun 30 2019, 12:36:01)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1acf1b0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 177648 bytes (173 KB) for 1 cores
*** Operational MODE: single process ***
Traceback (most recent call last):
  File "./mywebsite/wsgi.py", line 12, in <module>
    from django.core.wsgi import get_wsgi_application
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/core/wsgi.py", line 2, in <module>
    from django.core.handlers.wsgi import WSGIHandler
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/core/handlers/wsgi.py", line 8, in <module>
    from django.core.handlers import base
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/core/handlers/base.py", line 8, in <module>
    from django.urls import get_resolver, set_urlconf
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/urls/__init__.py", line 1, in <module>
    from .base import (
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/urls/base.py", line 8, in <module>
    from .exceptions import NoReverseMatch, Resolver404
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/urls/exceptions.py", line 1, in <module>
    from django.http import Http404
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/http/__init__.py", line 5, in <module>
    from django.http.response import (
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/http/response.py", line 15, in <module>
    from django.core.serializers.json import DjangoJSONEncoder
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/core/serializers/__init__.py", line 23, in <module>
    from django.core.serializers.base import SerializerDoesNotExist
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/core/serializers/base.py", line 7, in <module>
    from django.db import models
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/db/models/__init__.py", line 28, in <module>
    from django.db.models.base import DEFERRED, Model  # isort:skip
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
MemoryError
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 25158)
spawned uWSGI worker 1 (pid: 25159, cores: 1)
--- no python application found, check your startup logs for errors ---
foolpanda.com [pid: 25159|app: -1|req: -1/1] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 16:13:13 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
foolpanda.com [pid: 25159|app: -1|req: -1/2] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 16:13:14 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
*** Starting uWSGI 2.0.18 (64bit) on [Mon Jul  1 16:13:53 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 30 June 2019 12:33:41
os: Linux-3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019
nodename: VM_0_17_centos
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/django/mywebsite
writing pidfile to /root/django/mywebsite/script/uwsgi.pid
detected binary path: /root/.pyenv/versions/3.7.3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/django/mywebsite/
your processes number limit is 3881
limiting address space of processes...
your process address space limit is 536870912 bytes (512 MB)
your memory page size is 4096 bytes
detected max file descriptor number: 100001
VirtualHosting mode enabled.
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.1:9090).
bind(): Address already in use [core/socket.c line 769]
--- no python application found, check your startup logs for errors ---
foolpanda.com [pid: 25159|app: -1|req: -1/3] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 16:13:55 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
foolpanda.com [pid: 25159|app: -1|req: -1/4] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 16:13:57 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
*** Starting uWSGI 2.0.18 (64bit) on [Mon Jul  1 16:14:18 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 30 June 2019 12:33:41
os: Linux-3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019
nodename: VM_0_17_centos
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/django/mywebsite
writing pidfile to /root/django/mywebsite/script/uwsgi.pid
detected binary path: /root/.pyenv/versions/3.7.3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/django/mywebsite/
your processes number limit is 3881
limiting address space of processes...
your process address space limit is 1073741824 bytes (1024 MB)
your memory page size is 4096 bytes
detected max file descriptor number: 100001
VirtualHosting mode enabled.
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.1:9090).
bind(): Address already in use [core/socket.c line 769]
--- no python application found, check your startup logs for errors ---
foolpanda.com [pid: 25159|app: -1|req: -1/5] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 16:14:20 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
foolpanda.com [pid: 25159|app: -1|req: -1/6] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 16:14:21 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
foolpanda.com [pid: 25159|app: -1|req: -1/7] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 16:14:21 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
*** Starting uWSGI 2.0.18 (64bit) on [Mon Jul  1 16:14:58 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 30 June 2019 12:33:41
os: Linux-3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019
nodename: VM_0_17_centos
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/django/mywebsite
writing pidfile to /root/django/mywebsite/script/uwsgi.pid
detected binary path: /root/.pyenv/versions/3.7.3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/django/mywebsite/
your processes number limit is 3881
your memory page size is 4096 bytes
detected max file descriptor number: 100001
VirtualHosting mode enabled.
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.1:9090).
bind(): Address already in use [core/socket.c line 769]
--- no python application found, check your startup logs for errors ---
foolpanda.com [pid: 25159|app: -1|req: -1/8] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 16:15:00 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
foolpanda.com [pid: 25159|app: -1|req: -1/9] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 16:15:01 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
foolpanda.com [pid: 25159|app: -1|req: -1/10] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 16:15:01 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
foolpanda.com [pid: 25159|app: -1|req: -1/11] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 16:15:02 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
foolpanda.com [pid: 25159|app: -1|req: -1/12] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 16:15:02 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
foolpanda.com [pid: 25159|app: -1|req: -1/13] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 16:15:02 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
foolpanda.com [pid: 25159|app: -1|req: -1/14] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 16:15:03 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
foolpanda.com [pid: 25159|app: -1|req: -1/15] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 16:15:03 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
foolpanda.com [pid: 25159|app: -1|req: -1/16] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 16:15:04 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
*** Starting uWSGI 2.0.18 (64bit) on [Mon Jul  1 16:15:40 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 30 June 2019 12:33:41
os: Linux-3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019
nodename: VM_0_17_centos
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/django/mywebsite
writing pidfile to /root/django/mywebsite/script/uwsgi.pid
detected binary path: /root/.pyenv/versions/3.7.3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/django/mywebsite/
your processes number limit is 3881
your memory page size is 4096 bytes
detected max file descriptor number: 100001
VirtualHosting mode enabled.
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:9090 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.3 (default, Jun 30 2019, 12:36:01)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1bbc270
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 177648 bytes (173 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1bbc270 pid: 25739 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 25739)
spawned uWSGI worker 1 (pid: 25741, cores: 1)
foolpanda.com [pid: 25741|app: 0|req: 1/1] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 08:15:43 2019] GET / => generated 14 bytes in 8 msecs (HTTP/1.1 200) 3 headers in 108 bytes (1 switches on core 0)
foolpanda.com [pid: 25741|app: 0|req: 2/2] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 08:15:44 2019] GET / => generated 14 bytes in 0 msecs (HTTP/1.1 200) 3 headers in 108 bytes (1 switches on core 0)
foolpanda.com [pid: 25741|app: 0|req: 3/3] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 08:15:45 2019] GET / => generated 14 bytes in 0 msecs (HTTP/1.1 200) 3 headers in 108 bytes (1 switches on core 0)
foolpanda.com [pid: 25741|app: 0|req: 4/4] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 08:15:46 2019] GET / => generated 14 bytes in 0 msecs (HTTP/1.1 200) 3 headers in 108 bytes (1 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.18 (64bit) on [Mon Jul  1 16:16:26 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 30 June 2019 12:33:41
os: Linux-3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019
nodename: VM_0_17_centos
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/django/mywebsite
writing pidfile to /root/django/mywebsite/script/uwsgi.pid
detected binary path: /root/.pyenv/versions/3.7.3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/django/mywebsite/
your processes number limit is 3881
limiting address space of processes...
your process address space limit is 536870912 bytes (512 MB)
your memory page size is 4096 bytes
detected max file descriptor number: 100001
VirtualHosting mode enabled.
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:9090 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.3 (default, Jun 30 2019, 12:36:01)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x2a322a0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 177648 bytes (173 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x2a322a0 pid: 25910 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 25910)
spawned uWSGI worker 1 (pid: 25911, cores: 1)
foolpanda.com [pid: 25911|app: 0|req: 1/1] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 08:16:29 2019] GET / => generated 14 bytes in 8 msecs (HTTP/1.1 200) 3 headers in 108 bytes (1 switches on core 0)
foolpanda.com [pid: 25911|app: 0|req: 2/2] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 08:16:30 2019] GET / => generated 14 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 108 bytes (1 switches on core 0)
foolpanda.com [pid: 25911|app: 0|req: 3/3] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 08:16:30 2019] GET / => generated 14 bytes in 0 msecs (HTTP/1.1 200) 3 headers in 108 bytes (1 switches on core 0)
foolpanda.com [pid: 25911|app: 0|req: 4/4] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 08:16:31 2019] GET / => generated 14 bytes in 0 msecs (HTTP/1.1 200) 3 headers in 108 bytes (1 switches on core 0)
foolpanda.com [pid: 25911|app: 0|req: 5/5] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 08:16:31 2019] GET / => generated 14 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 108 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.18 (64bit) on [Mon Jul  1 16:16:43 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 30 June 2019 12:33:41
os: Linux-3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019
nodename: VM_0_17_centos
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/django/mywebsite
writing pidfile to /root/django/mywebsite/script/uwsgi.pid
detected binary path: /root/.pyenv/versions/3.7.3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/django/mywebsite/
your processes number limit is 3881
limiting address space of processes...
your process address space limit is 536870912 bytes (512 MB)
your memory page size is 4096 bytes
detected max file descriptor number: 100001
VirtualHosting mode enabled.
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:9090 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.3 (default, Jun 30 2019, 12:36:01)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1cd92a0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 177648 bytes (173 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1cd92a0 pid: 25978 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 25978)
spawned uWSGI worker 1 (pid: 25979, cores: 1)
foolpanda.com [pid: 25979|app: 0|req: 1/1] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 08:16:45 2019] GET / => generated 14 bytes in 8 msecs (HTTP/1.1 200) 3 headers in 108 bytes (1 switches on core 0)
foolpanda.com [pid: 25979|app: 0|req: 2/2] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 08:16:46 2019] GET / => generated 14 bytes in 0 msecs (HTTP/1.1 200) 3 headers in 108 bytes (1 switches on core 0)
foolpanda.com [pid: 25979|app: 0|req: 3/3] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 08:16:47 2019] GET / => generated 14 bytes in 0 msecs (HTTP/1.1 200) 3 headers in 108 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.18 (64bit) on [Mon Jul  1 16:17:41 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 30 June 2019 12:33:41
os: Linux-3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019
nodename: VM_0_17_centos
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/django/mywebsite
writing pidfile to /root/django/mywebsite/script/uwsgi.pid
detected binary path: /root/.pyenv/versions/3.7.3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/django/mywebsite/
your processes number limit is 3881
limiting address space of processes...
your process address space limit is 536870912 bytes (512 MB)
your memory page size is 4096 bytes
detected max file descriptor number: 100001
VirtualHosting mode enabled.
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:9090 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.3 (default, Jun 30 2019, 12:36:01)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x13382d0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 177648 bytes (173 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x13382d0 pid: 26144 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 26144)
spawned uWSGI worker 1 (pid: 26145, cores: 1)
foolpanda.com [pid: 26145|app: 0|req: 1/1] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 08:17:42 2019] GET / => generated 14 bytes in 8 msecs (HTTP/1.1 200) 3 headers in 108 bytes (1 switches on core 0)
foolpanda.com [pid: 26145|app: 0|req: 2/2] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 08:17:43 2019] GET / => generated 14 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 108 bytes (1 switches on core 0)
foolpanda.com [pid: 26145|app: 0|req: 3/3] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 08:17:43 2019] GET / => generated 14 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 108 bytes (1 switches on core 0)
foolpanda.com [pid: 26145|app: 0|req: 4/4] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 08:17:44 2019] GET / => generated 14 bytes in 0 msecs (HTTP/1.1 200) 3 headers in 108 bytes (1 switches on core 0)
foolpanda.com [pid: 26145|app: 0|req: 5/5] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 08:17:44 2019] GET / => generated 14 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 108 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.18 (64bit) on [Mon Jul  1 16:21:45 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 30 June 2019 12:33:41
os: Linux-3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019
nodename: VM_0_17_centos
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/django/mywebsite
writing pidfile to /root/django/mywebsite/script/uwsgi.pid
detected binary path: /root/.pyenv/versions/3.7.3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/django/mywebsite/
your processes number limit is 3881
limiting address space of processes...
your process address space limit is 536870912 bytes (512 MB)
your memory page size is 4096 bytes
detected max file descriptor number: 100001
VirtualHosting mode enabled.
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:9090 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.3 (default, Jun 30 2019, 12:36:01)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1ad7300
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 355296 bytes (346 KB) for 3 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x1ad7300 pid: 26697 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 26697)
spawned uWSGI worker 1 (pid: 26698, cores: 1)
spawned uWSGI worker 2 (pid: 26699, cores: 1)
spawned uWSGI worker 3 (pid: 26700, cores: 1)
foolpanda.com [pid: 26700|app: 0|req: 1/1] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 08:22:12 2019] GET / => generated 14 bytes in 7 msecs (HTTP/1.1 200) 3 headers in 108 bytes (1 switches on core 0)
foolpanda.com [pid: 26700|app: 0|req: 2/2] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 08:22:14 2019] GET / => generated 14 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 108 bytes (1 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
*** Starting uWSGI 2.0.18 (64bit) on [Mon Jul  1 16:39:27 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 30 June 2019 12:33:41
os: Linux-3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019
nodename: VM_0_17_centos
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/django/mywebsite
writing pidfile to /root/django/mywebsite/script/uwsgi.pid
detected binary path: /root/.pyenv/versions/3.7.3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/django/mywebsite/
your processes number limit is 3881
limiting address space of processes...
your process address space limit is 536870912 bytes (512 MB)
your memory page size is 4096 bytes
detected max file descriptor number: 100001
VirtualHosting mode enabled.
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /root/django/mywebsite/script/uwsgi.sock fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.3 (default, Jun 30 2019, 12:36:01)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xba2e90
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 355296 bytes (346 KB) for 3 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0xba2e90 pid: 29043 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 29043)
spawned uWSGI worker 1 (pid: 29045, cores: 1)
spawned uWSGI worker 2 (pid: 29046, cores: 1)
spawned uWSGI worker 3 (pid: 29047, cores: 1)
foolpanda.com [pid: 29047|app: 0|req: 1/1] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 08:46:15 2019] GET / => generated 14 bytes in 8 msecs (HTTP/1.1 200) 3 headers in 108 bytes (1 switches on core 0)
foolpanda.com [pid: 29045|app: 0|req: 1/2] 59.108.165.58 () {44 vars in 768 bytes} [Mon Jul  1 08:46:16 2019] GET / => generated 14 bytes in 8 msecs (HTTP/1.1 200) 3 headers in 108 bytes (1 switches on core 0)
Not Found: /manager/html
129.28.167.123 [pid: 29047|app: 0|req: 2/3] 31.45.240.114 () {40 vars in 576 bytes} [Mon Jul  1 09:37:41 2019] GET /manager/html => generated 2080 bytes in 8 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
